# 1/If you haven’t done so already, complete the instructions in the Exercise for creating the “price_label” and “busiest_day” columns.

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# creating path
path = r'C:\Users\bouas\instacart bascket analysis'

In [3]:
# The read_pickle() function doesn't accept index_col parameter
# Simply remove the index_col argument
ords_prods_merge = pd.read_pickle(os.path.join(path, 'data', 'prepared_data', 'ords_prods_merge.pkl'))

# If you need to reset the index after loading, you can do:
# df = df.reset_index(drop=True)

In [4]:
df = ords_prods_merge[:1000000]

#### If-Statements with User-Defined Functions

In [5]:
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [6]:
df['price_range'] = df.apply(price_label, axis=1)

C:\Users\bouas\AppData\Local\Temp\ipykernel_41784\2848743372.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis=1)

In [7]:
df['price_range'].value_counts(dropna = False)

price_range
Mid-range product    652593
Low-range product    338063
High range             9344
Name: count, dtype: int64

In [8]:
df['prices'].max()

24.5

In [9]:
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

C:\Users\bouas\AppData\Local\Temp\ipykernel_41784\1169838859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [10]:
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [11]:
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [12]:
df['price_range_loc'].value_counts(dropna = False)

price_range_loc
Mid-range product     652593
Low-range product     338063
High-range product      9344
Name: count, dtype: int64

#### If-Statements with the loc() Function

In [13]:
ords_prods_merge.loc[ords_prods_merge['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [14]:
ords_prods_merge.loc[(ords_prods_merge['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [15]:
ords_prods_merge.loc[ords_prods_merge['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [16]:
ords_prods_merge['price_range_loc'].value_counts(dropna = False)

price_range_loc
NaN                   21209404
Low-range product     10126366
Mid-range product       652593
High-range product      417678
Name: count, dtype: int64

In [17]:
ords_prods_merge.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,1,11,7.0,7.0,0.0,both,Mid-range product
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,1,14,1.0,3.0,1.0,both,Mid-range product
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,0,14,7.0,4.0,1.0,both,Mid-range product
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,2,10,30.0,2.0,0.0,both,Mid-range product
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,1,15,NaN,30.0,0.0,both,Mid-range product

#### If-Statements with For-Loops

In [18]:
result = []

for value in ords_prods_merge["order_dow"]:
  if value == 0:
    result.append("Busiest day")
  elif value == 4:
    result.append("Least busy")
  else:
    result.append("Regularly busy")

In [19]:
result[:10]

['Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy']

In [20]:
# creation of column
ords_prods_merge['Busiest day'] = result

In [21]:
ords_prods_merge['Busiest day'].value_counts(dropna = False)

Busiest day
Regularly busy    22417684
Busiest day        6204404
Least busy         3783953
Name: count, dtype: int64

#  2/Now, they want “Busiest day” to become “Busiest days” (plural). This label should correspond with the two busiest days of the week as opposed to the single busiest day.

#### Searching for the top busiest 2 days and least busy

In [22]:
ords_prods_merge['order_dow'].value_counts(dropna = False)

order_dow
0    6204404
1    5660456
6    4496635
2    4213986
5    4205906
3    3840701
4    3783953
Name: count, dtype: int64

#### processing to get result

In [23]:
result_2 = []

for value in ords_prods_merge["order_dow"]:
    if value >= 0 and value <= 1:
        result_2.append("Busiest days")
    elif value >= 3 and value <= 4:
        result_2.append("Least busy")
    else:
        result_2.append("Regularly busy")

In [24]:
# creation of column
ords_prods_merge['Busiest days'] = result_2

# 3/Check the values of this new column for accuracy. Note any observations in markdown format.

In [25]:
ords_prods_merge['Busiest days'].value_counts(dropna = False)

Busiest days
Regularly busy    12916527
Busiest days      11864860
Least busy         7624654
Name: count, dtype: int64

#### No NaN values appear, This means that all rows have been labeled.
#### So the condition covers all possible cases.
#### All three categories are present(2,2,3)
#### The majority of days fall into "Regularly busy," which makes sense: most days are neither extreme nor exceptional.

# 4/The senior technical officer at Instacart wants you to identify the busiest hours of the day. Rather than by hour, they want periods of time labeled “Most orders,” “Average orders,” and “Fewest orders.” Create a new column containing these labels called “busiest_period_of_day.”

## search for the partition method

In [26]:
ords_prods_merge['order_hour_of_day'].value_counts(dropna = False)

order_hour_of_day
10    2761862
11    2736242
14    2689251
15    2662246
13    2661057
12    2618613
16    2535313
9     2454273
17    2087721
8     1718182
18    1636566
19    1258352
20     976182
7      891082
21     795658
22     634247
23     402335
6      290500
0      218786
1      115706
5       87964
2       69377
4       53245
3       51281
Name: count, dtype: int64

### processing

In [27]:
# Fewest orders : 0–7
ords_prods_merge.loc[(ords_prods_merge['order_hour_of_day'] >= 0) & (ords_prods_merge['order_hour_of_day'] <= 7),
       'busiest_period_of_day'] = 'Fewest orders'

In [28]:
# Most orders : 8–15
ords_prods_merge.loc[(ords_prods_merge['order_hour_of_day'] >= 8) & (ords_prods_merge['order_hour_of_day'] <= 15),
       'busiest_period_of_day'] = 'Most orders'

In [29]:
# Average orders : 16–23
ords_prods_merge.loc[(ords_prods_merge['order_hour_of_day'] >= 16) & (ords_prods_merge['order_hour_of_day'] <= 23),
       'busiest_period_of_day'] = 'Average orders'

### Results 
##### General results of the excercie + task

In [31]:
ords_prods_merge.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,1,11,7.0,7.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,1,14,1.0,3.0,1.0,both,Mid-range product,Regularly busy,Busiest days,Most orders
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,0,14,7.0,4.0,1.0,both,Mid-range product,Busiest day,Busiest days,Most orders
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,2,10,30.0,2.0,0.0,both,Mid-range product,Regularly busy,Regularly busy,Most orders
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,1,15,NaN,30.0,0.0,both,Mid-range product,Regularly busy,Busiest days,Most orders

# 5/Print the frequency for this new column.

In [32]:
ords_prods_merge['busiest_period_of_day'].value_counts(dropna = False)

busiest_period_of_day
Most orders       20301726
Average orders    10326374
Fewest orders      1777941
Name: count, dtype: int64

In [33]:
ords_prods_merge.to_pickle(os.path.join(path, 'data','prepared_data', 'Deriving New Variables.pkl'))