# -------------Part 1 : Intro to data visualisation-----------------

# 3/Import your analysis libraries, as well as your new customer data set as a dataframe.

In [1]:
# creating libraries
import pandas as pd
import numpy as np
import os

In [2]:
# creating path
path = r'C:\Users\bouas\instacart bascket analysis'
customers =pd.read_csv(os.path.join(path, 'data', 'original_data', 'customers.csv'))

### Exploratory Data Analysis (EDA)

In [3]:
# defining df
df = customers

In [4]:
# displaying columns
df.columns

Index(['user_id', 'First Name', 'Surnam', 'Gender', 'STATE', 'Age',
       'date_joined', 'n_dependants', 'fam_status', 'income'],
      dtype='object')

In [5]:
# displaying columns and rows counts
df.shape

(206209, 10)

In [6]:
# head of df
df.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [7]:
# displaying some statistic
df.describe()

             user_id            Age   n_dependants         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

# 4/Wrangle the data so that it follows consistent logic; for example, rename columns with illogical names and drop columns that don’t add anything to your analysis.

### we already have user id , we dont need the name and familiar name for our analysis , so we can drop both columns

In [8]:
df = df.drop(columns=['First Name'])

In [9]:
df = df.drop(columns=['Surnam'])

### making some clarifications for the depeendents counts , familiar satus  and transform the first letter to lowercase , in order to make the coding more easier for our analysis

In [10]:
df.rename(columns = {'n_dependants' : 'household_dependents'}, inplace = True)

In [11]:
df.rename(columns = {'fam_status' : 'familiar_status'}, inplace = True)

In [12]:
df.rename(columns = {'Age' : 'age'}, inplace = True)

In [13]:
df.rename(columns = {'Gender' : 'gender'}, inplace = True)

In [14]:
df.head(1)

,user_id,gender,STATE,age,date_joined,household_dependents,familiar_status,income
0,26711,Female,Missouri,48,1/1/2017,3,married,165665

# 5/Complete the fundamental data quality and consistency checks you’ve learned throughout this Achievement; for example, check for and address missing values and duplicates, and convert any mixed-type data.

##### cheking missing values

In [15]:
df.isnull().sum()

user_id                 0
gender                  0
STATE                   0
age                     0
date_joined             0
household_dependents    0
familiar_status         0
income                  0
dtype: int64

##### >>>> No missing values

##### checking for mixed type data

In [16]:

df.dtypes

user_id                  int64
gender                  object
STATE                   object
age                      int64
date_joined             object
household_dependents     int64
familiar_status         object
income                   int64
dtype: object

##### >>>> no mixed type data

##### checking for duplicate

In [17]:

df_dup= df[df.duplicated()]

In [18]:

df_dup

Empty DataFrame
Columns: [user_id, gender, STATE, age, date_joined, household_dependents, familiar_status, income]
Index: []

##### >>>> No duplicate values

#### adding df

In [19]:
grouping_data_order_product = pd.read_pickle(os.path.join(path, 'data', 'prepared_data', 'grouping_data_order_product.pkl'))

In [20]:
# defining df
df2= grouping_data_order_product

In [21]:
# displaying and cheking rows and columns
df2.shape

(32406041, 26)

In [22]:
# cheking head
df2.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,...,price_range_loc,Busiest day,Busiest days,busiest_period_of_day,max_order,loyalty_flag,mean_price,spending_flag,median_days_since_last_orders,order_frequency_flag
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,...,Mid-range product,Regularly busy,Busiest days,Most orders,4,New customer,7.163333,Low spender,30.0,Non-frequent customer
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,...,Mid-range product,Regularly busy,Busiest days,Most orders,99,Loyal customer,5.342729,Low spender,1.0,Frequent customer
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,...,Mid-range product,Busiest day,Busiest days,Most orders,23,Regular customer,7.469540,Low spender,7.0,Frequent customer
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,...,Mid-range product,Regularly busy,Regularly busy,Most orders,5,New customer,6.986207,Low spender,30.0,Non-frequent customer
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,...,Mid-range product,Regularly busy,Busiest days,Most orders,22,Regular customer,7.493154,Low spender,7.0,Frequent customer

In [23]:
df2.columns

Index(['Unnamed: 0', 'product_id', 'product_name', 'aisle_id', 'department_id',
       'prices', 'order_id', 'user_id', 'eval_set', 'order_number',
       'order_dow', 'order_hour_of_day', 'days_since_prior_order',
       'add_to_cart_order', 'reordered', '_merge', 'price_range_loc',
       'Busiest day', 'Busiest days', 'busiest_period_of_day', 'max_order',
       'loyalty_flag', 'mean_price', 'spending_flag',
       'median_days_since_last_orders', 'order_frequency_flag'],
      dtype='object')

# 6/Combine your customer data with the rest of your prepared Instacart data. (Hint: Make sure the key columns are the same data type!)

##### first merging

In [24]:
pd.merge(df2,df, on = ['user_id'], indicator='Match')

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,...,median_days_since_last_orders,order_frequency_flag,gender,STATE,age,date_joined,household_dependents,familiar_status,income,Match
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,...,30.0,Non-frequent customer,Female,District of Columbia,68,6/30/2019,2,married,142744,both
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,...,1.0,Frequent customer,Male,New York,48,4/29/2018,2,married,43906,both
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,...,7.0,Frequent customer,Female,Massachusetts,31,3/11/2017,2,married,78505,both
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,...,30.0,Non-frequent customer,Male,Tennessee,65,10/27/2019,1,married,51010,both
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,...,7.0,Frequent customer,Male,New Jersey,75,4/9/2019,3,married,115468,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32406036,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3111954,79411,prior,6,...,7.0,Frequent customer,Male,Arkansas,50,7/13/2019,1,married,149398,both
32406037,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3122003,146323,prior,3,...,24.0,Non-frequent customer,Male,Arkansas,52,1/29/2017,3,married,117424,both
32406038,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3166828,188073,prior,7,...,8.0,Frequent customer,Female,Minnesota,20,1/23/2018,2,living with parents and siblings,27577,both
32406039,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3290206,121646,prior,3,...,28.0,Non-frequent customer,Female,Georgia,45,11/18/2017,1,married,102081,both
32406040,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3401313,200377,prior,1,...,30.0,Non-frequent customer,Male,West Virginia,25,3/16/2020,0,single,53936,both

##### deleating merge column from df2

In [25]:
df2 = df2.drop(['_merge'], axis=1)

#### final merging

In [26]:
df_final_merge =df.merge(df2, on = 'user_id', indicator = True)

In [27]:
df_final_merge.columns

Index(['user_id', 'gender', 'STATE', 'age', 'date_joined',
       'household_dependents', 'familiar_status', 'income', 'Unnamed: 0',
       'product_id', 'product_name', 'aisle_id', 'department_id', 'prices',
       'order_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'add_to_cart_order',
       'reordered', 'price_range_loc', 'Busiest day', 'Busiest days',
       'busiest_period_of_day', 'max_order', 'loyalty_flag', 'mean_price',
       'spending_flag', 'median_days_since_last_orders',
       'order_frequency_flag', '_merge'],
      dtype='object')

In [28]:
df_final_merge.shape

(32406041, 33)

##### cheking merge...

In [29]:
df_final_merge['_merge'].value_counts()

_merge
both          32406041
left_only            0
right_only           0
Name: count, dtype: int64

### >>> The merging was successful.

In [30]:
# exporting the dataframe 
df_final_merge.to_pickle(os.path.join(path, 'data','prepared_data', 'intro_to_data_410.pkl'))