# Exercice Merging Your Instacart Data

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = r'C:\Users\bouas\instacart bascket analysis'

df_ords_prior= pd.read_csv(os.path.join(path, 'data', 'original_data', 'orders_products_prior.csv'), index_col = False)

df = pd.read_csv(os.path.join(path, 'data', 'original_data', 'orders.csv'), index_col = False)

In [3]:
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [8]:
df_ords_prior.shape

(32434489, 4)

In [9]:
df.shape

(3421083, 7)

# Merging Your Instacart Data

In [6]:
df_merged_large = df.merge(df_ords_prior, on = 'order_id', indicator =True)

In [7]:
df_merged_large

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,prior,1,2,8,NaN,196,1,0,both
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both
...,...,...,...,...,...,...,...,...,...,...,...
32434484,2977660,206209,prior,13,1,12,7.0,14197,5,1,both
32434485,2977660,206209,prior,13,1,12,7.0,38730,6,0,both
32434486,2977660,206209,prior,13,1,12,7.0,31477,7,0,both
32434487,2977660,206209,prior,13,1,12,7.0,6567,8,0,both
32434488,2977660,206209,prior,13,1,12,7.0,22920,9,0,both

In [8]:

df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only            0
right_only           0
Name: count, dtype: int64

In [9]:
df_merged_large = df.merge(df_ords_prior, on = 'order_id', indicator = True, how='outer')

In [10]:
df_merged_large['_merge'].value_counts()

_merge
both          32434489
left_only       206209
right_only           0
Name: count, dtype: int64

In [11]:
# Export data to csv

df_merged_large.to_csv(os.path.join(path, 'data','prepared_data', 'orders_products_combined.csv'))

# Export data to pkl

df_merged_large.to_pickle(os.path.join(path, 'data','prepared_data', 'orders_products_combined.pkl'))