In [3]:
import pandas as pd
import numpy as np
import os

# 3/In a new notebook, import the orders_products_combined dataframe from the pickle file you just saved.

In [4]:
# importing df
path = r'C:\Users\bouas\instacart bascket analysis'
orders_products_combined = pd.read_pickle(os.path.join(path, 'data', 'prepared_data', 'orders_products_combined.pkl'))
prods_consistency= pd.read_csv(os.path.join(path, 'data', 'prepared_data', 'prods_consistency.csv'), index_col = False)

# 3/Check the shape of the imported dataframe

In [5]:
orders_products_combined.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1,112108,train,4,4,10,9.0,NaN,NaN,NaN,left_only
1,2,202279,prior,3,5,9,8.0,33120.0,1.0,1.0,both
2,2,202279,prior,3,5,9,8.0,28985.0,2.0,1.0,both
3,2,202279,prior,3,5,9,8.0,9327.0,3.0,0.0,both
4,2,202279,prior,3,5,9,8.0,45918.0,4.0,1.0,both

In [6]:
prods_consistency.shape

(49677, 6)

In [7]:
orders_products_combined.shape

(32640698, 11)

# 4/Determine a suitable way to combine the orders_products_combined dataframe with your products data set

In [8]:
# searching for commun variable
prods_consistency

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices
0,0,1,Chocolate Sandwich Cookies,61,19,5.8
1,1,2,All-Seasons Salt,104,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,4,5,Green Chile Anytime Sauce,5,13,4.3
...,...,...,...,...,...,...
49672,49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3
49673,49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.1
49674,49690,49686,Artisan Baguette,112,3,7.8
49675,49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.7
49676,49692,49688,Fresh Foaming Cleanser,73,11,13.5

##### >>> we will use product_id

### Merging...

In [9]:
#  Merging without overwriting
pd.merge(orders_products_combined,prods_consistency, on = ['product_id'], indicator='Match')

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,Unnamed: 0,product_name,aisle_id,department_id,prices,Match
0,2,202279,prior,3,5,9,8.0,33120.0,1.0,1.0,both,33122,Organic Egg Whites,86,16,11.3,both
1,2,202279,prior,3,5,9,8.0,28985.0,2.0,1.0,both,28987,Michigan Organic Kale,83,4,13.4,both
2,2,202279,prior,3,5,9,8.0,9327.0,3.0,0.0,both,9327,Garlic Powder,104,13,3.6,both
3,2,202279,prior,3,5,9,8.0,45918.0,4.0,1.0,both,45922,Coconut Butter,19,13,8.4,both
4,2,202279,prior,3,5,9,8.0,30035.0,5.0,0.0,both,30037,Natural Sweetener,17,13,13.7,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32406036,3421083,25247,prior,24,2,6,21.0,39678.0,6.0,1.0,both,39682,Free & Clear Natural Dishwasher Detergent,74,17,7.1,both
32406037,3421083,25247,prior,24,2,6,21.0,11352.0,7.0,0.0,both,11352,Organic Mini Sandwich Crackers Peanut Butter,78,19,2.8,both
32406038,3421083,25247,prior,24,2,6,21.0,4600.0,8.0,0.0,both,4600,All Natural French Toast Sticks,52,1,5.8,both
32406039,3421083,25247,prior,24,2,6,21.0,24852.0,9.0,1.0,both,24853,Banana,24,4,12.3,both
32406040,3421083,25247,prior,24,2,6,21.0,5020.0,10.0,1.0,both,5020,Organic Sweet & Salty Peanut Pretzel Granola ...,3,19,3.2,both

###### dropping merge of order product combined so we can do the merge flag

In [10]:
orders_products_combined = orders_products_combined.drop(['_merge'], axis=1)

In [11]:
orders_products_combined.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1,112108,train,4,4,10,9.0,NaN,NaN,NaN
1,2,202279,prior,3,5,9,8.0,33120.0,1.0,1.0
2,2,202279,prior,3,5,9,8.0,28985.0,2.0,1.0
3,2,202279,prior,3,5,9,8.0,9327.0,3.0,0.0
4,2,202279,prior,3,5,9,8.0,45918.0,4.0,1.0

In [12]:
orders_products_combined.shape

(32640698, 10)

# 6/Confirm the results of the merge using the merge flag

In [13]:
df_ords_prods_merge = prods_consistency.merge(orders_products_combined, on = 'product_id', indicator = True)

In [14]:
df_ords_prods_merge.head()

,Unnamed: 0,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1107,38259,prior,2,1,11,7.0,7.0,0.0,both
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,5319,196224,prior,65,1,14,1.0,3.0,1.0,both
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,7540,138499,prior,8,0,14,7.0,4.0,1.0,both
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,9228,79603,prior,2,2,10,30.0,2.0,0.0,both
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,9273,50005,prior,1,1,15,NaN,30.0,0.0,both

In [15]:
# checking shape
df_ords_prods_merge.shape

(32406041, 16)

In [16]:
# showing results of merge flag
df_ords_prods_merge['_merge'].value_counts()

_merge
both          32406041
left_only            0
right_only           0
Name: count, dtype: int64

In [17]:
df_ords_prods_merge.to_pickle(os.path.join(path, 'data','prepared_data', 'ords_prods_merge.pkl'))